#!/bin/bash
if [ -z "$PYFILE" ]; then
  echo "PYFILE is not set. Please provide the Python file to compile."
  exit 1
fi
OUTFILE="${PYFILE}c"
python3 -m compileall -b -x __pycache__ -l -- "$PYFILE"
mv "__pycache__/${PYFILE}.pyc" "$OUTFILE"
